# Generated by Django 4.2.5 on 2023-09-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nature",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "income"), (1, "expense"), (2, "investment")]
                    ),
                ),
                ("effective_date", models.DateField()),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
