# Generated by Django 4.2.5 on 2023-09-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movement",
            options={"ordering": ("-effective_date",)},
        ),
        migrations.AddField(
            model_name="movement",
            name="category",
            field=models.TextField(default="undefined"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movement",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
